Carouselforthreeimages
WildCodeSchool/2022-09-JS-RMT-JSCREW-projet2-team3 pull request #18
Opened 2022-11-07 22:37 UTC by serpentaire

2022-11-08 09:56 UTC, Charliepian approved these changes

2022-11-08 09:58 UTC, arouxel17 approved these changes

2022-11-08 15:13 UTC, jujuck requested changes

2022-11-08 15:13 UTC, jujuck commented on frontend/src/components/Carouseltroisfilm.jsx
> +            onClick={() => openPageOneProduct(filmsData[filmId1])}
J'ai un doute, n'est il pas possible de rendre <OneProduct /> directement dans la fonction

2022-11-08 15:13 UTC, jujuck commented on frontend/src/components/Footer.jsx
> +        `Bonjour ${name} votre message ${message} et votre inscription ont bien été pris en compte, un mail de confirmation vous a été envoyé à l'adresse ${email}`,
En Anglais ???

2022-11-08 15:13 UTC, jujuck commented on frontend/src/components/Carouseltroisfilm.jsx
> +  const filmId1 = Math.floor(Math.random() * filmsData.length);
Créer une fonction pour le random et appelle la directement dans filmsData[getRandom()]

2022-11-08 21:26 UTC, serpentaire commented on frontend/src/components/Carouseltroisfilm.jsx
> +  const filmId1 = Math.floor(Math.random() * filmsData.length);
Pour moi si je fais ça, lorsque je vais cliquer sur l'image je ne récupèrerai pas le même ID que celle de l'image puisque le clic lancera un nouveau calcul random.

2022-11-08 21:32 UTC, serpentaire commented on frontend/src/components/Carouseltroisfilm.jsx
> +            onClick={() => openPageOneProduct(filmsData[filmId1])}
En fait comme je n'arrive pas à ouvrir oneproduct j'ai fait cette fonction pour y mettre un console.log afin de voir si je récupérai bien mon objet . Il s'avère que oui mais la page ne s'ouvre pas. donc j'ai supprimer le console.log et laissé comme ça. j'ai fait la PR pour enregistrer ce qui est fait. Qui est en fait la création du carrousel.

2022-11-09 08:34 UTC, Charliepian approved these changes

2022-11-09 13:01 UTC, jujuck approved these changes

2022-11-09 13:01 UTC, merged