Navbar
WildCodeSchool/2022-09-JS-RMT-JSCREW-projet2-team3 pull request #3
Opened 2022-11-02 08:24 UTC by Charliepian

2022-11-02 08:25 UTC, jordanvax submitted a review, later dismissed
top

2022-11-02 08:26 UTC, arouxel17 submitted a review, later dismissed

2022-11-02 09:09 UTC, jujuck requested changes

2022-11-02 09:09 UTC, jujuck commented on frontend/src/App.jsx
> +
Réorganise les imports en premier les modules react, puis les pages, puis les composants et puis le CSS ou data

2022-11-02 09:09 UTC, jujuck commented on frontend/src/components/NavBar.jsx
> +        <button
Mise en place d'un composant réutilisable NavButton.jsx et passage de Props

2022-11-02 09:09 UTC, jujuck commented on frontend/src/App.jsx
>        <Subscribe />
La page subscribe est elle également concerné par la nav ??? si oui, mettre le conditionnel

2022-11-02 09:09 UTC, jujuck commented on frontend/src/App.jsx
> +      {page === "Home" ? <Home filmsData={filmsData} /> : ""}
Remplacer les ternaires pas un conditionnel en && {page === "home" && <Home filmsData={filmsData} />

2022-11-03 07:39 UTC, serpentaire approved these changes

2022-11-03 07:46 UTC, serpentaire submitted a review, later dismissed

2022-11-03 11:13 UTC, jujuck approved these changes

2022-11-03 11:25 UTC, arouxel17 approved these changes

2022-11-03 11:25 UTC, jujuck approved these changes

2022-11-03 11:27 UTC, jordanvax approved these changes

2022-11-03 11:27 UTC, merged