Movie card
WildCodeSchool/2022-09-JS-RMT-JSCREW-projet2-team3 pull request #4
Opened 2022-11-02 09:00 UTC by Samarcande86

2022-11-02 09:07 UTC, arouxel17 submitted a review, later dismissed
good

2022-11-02 15:22 UTC, jordanvax approved these changes
top

2022-11-03 13:39 UTC, jujuck requested changes

2022-11-03 13:39 UTC, jujuck commented on frontend/src/pages/OneProduct.jsx
> +            <b>Vote{filmData.vote_average}</b>
Un espace entre vote et ta variable

2022-11-03 13:39 UTC, jujuck commented on frontend/src/pages/OneProduct.css
> +  color: white;
Mets directment la class Bootstrap sur l'element

2022-11-03 14:31 UTC, arouxel17 submitted a review, later dismissed

2022-11-03 14:32 UTC, jordanvax approved these changes

2022-11-03 14:35 UTC, arouxel17 approved these changes

2022-11-03 14:37 UTC, jordanvax approved these changes

2022-11-03 16:41 UTC, jujuck approved these changes

2022-11-03 16:41 UTC, merged