Connection de threefilm à la db
WildCodeSchool/2022-09-JS-RMT-JSCREW-projet2-team3 pull request #52
Opened 2022-11-20 17:55 UTC by serpentaire

2022-11-20 20:31 UTC, arouxel17 approved these changes

2022-11-21 06:13 UTC, Charliepian approved these changes

2022-11-21 08:56 UTC, jujuck requested changes

2022-11-21 08:56 UTC, jujuck commented on frontend/src/components/Carrousel/Threefilm.jsx
> +  let filmId1 = 1;
A faire directement dans les attributs en JSX (dans les balises du return)

2022-11-21 10:32 UTC, arouxel17 approved these changes

2022-11-21 10:32 UTC, Charliepian approved these changes

2022-11-21 16:27 UTC, jujuck approved these changes

2022-11-21 16:28 UTC, merged